# Site settings
title: GitContentSearch
description: "A free tool to search Git history for strings in Excel files (.xls, .xlsx) and text files using binary search. Perfect for legacy data tracking in Git repositories."
baseurl: "/GitContentSearch" # The subpath of your site, e.g., /GitContentSearch
url: "https://entityprocess.github.io" # Replace with your GitHub Pages URL

# SEO settings
permalink: pretty
plugins:
  - jekyll-seo-tag

# Optional: Theme (uncomment to use a different theme)
# theme: minima

# Markdown settings
markdown: kramdown