title: GitContentSearch
description: "A free tool to search Git history for strings in Excel files (.xls, .xlsx) and text files using binary search. Perfect for legacy data tracking in Git repositories."
baseurl: ""
url: "https://gitcontentsearch.entityprocess.com"
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
remote_theme: cotes2020/jekyll-theme-chirpy
markdown: kramdown